In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

# Data loading

In [3]:
df = pd.read_csv('dataset/data-pre-processing/Data.csv')

In [26]:
#X represents all the feature variables.
X = df.iloc[:,:-1].values
#Y represents the dependant variable
Y = df.iloc[:,-1].values

In [30]:
print(X,Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Handling missing values

In [27]:
from sklearn.impute import SimpleImputer
###Helps replace all missing fileds in with column average
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
###Find all the missing values.ake sure to choose numeric columns for this strategy
imputer.fit(X[:,1:3])
###Apply transform to missing values
X[:,1:3]=imputer.transform(X[:,1:3])

In [31]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding Categorical Data

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#apply onehot encoding to column 1 to transform categorical data into a numeric value
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [64]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


# Encoding Dependant Variables

In [65]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y=le.fit_transform(Y)

In [66]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into Training set and Test set

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [70]:
print(x_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [71]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [73]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [74]:
print(y_test)

[0 1]


# Feature scaling

In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,4:] = sc.fit_transform(x_train[:,4:])
x_test[:,4:] = sc.transform(x_test[:,4:])

In [76]:
print(x_train)

[[1.0 0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [1.0 0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [1.0 0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [77]:
print(x_test)

[[1.0 0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
